config/routes.rb
Rails.application.routes.draw do
  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags
  devise_for :users
    resources :links do
    member do
      put "like", to:    "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end
  root to: "links#index"
  

end

app/models/link.rb
class Link < ActiveRecord::Base
    acts_as_votable
    belongs_to :user
    has_many :comments, :dependent => :delete_all
    self.per_page = 10

    def ci_lower_bound(pos, n, confidence)
      if n == 0
          return 0.0
      end
      z = Statistics2.pnormaldist(1-(1-confidence)/2)
      phat = 1.0*pos/n
      ((phat + z*z/(2*n) - z * Math.sqrt((phat*(1-phat)+z*z/(4*n))/n))/(1+z*z/n)*100).round(2)
    end

  	def self.search(search)
    		where("title LIKE ?", "%#{search}%")
  	end

    validates :title, :url, presence: true
    validates :url, format: { with: /https?:\/\/(www\.)?[-a-zA-Z0-9@:%._\+~#=]{2,256}\.[a-z]{2,6}\b([-a-zA-Z0-9@:%_\+.~#?&\/=]*)?/, message: "jest niewłaściwy" }
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /links
  # GET /links.json
  def index
    if params[:search]
       @links = Link.all.search(params[:search]).paginate(page: params[:page], per_page: 10)
    elsif params[:my]
       @links = Link.all.paginate(page: params[:page], per_page: 10)
       @my = true
    elsif params[:all]
       @links = Link.all.paginate(page: params[:page], per_page: 10)
       @my = false
    elsif params[:sortDate]
      if params[:sortDate] == "desc"
        @links= Link.all.paginate(page: params[:page], per_page: 10).order('created_at DESC')
        @sd = true;
      else
        @links = Link.all.paginate(page: params[:page], per_page: 10).order('created_at ASC')
        @sd = false;
      end
    elsif params[:sortName]
      if params[:sortName] == "asc"
        @links = Link.all.paginate(page: params[:page], per_page: 10).order('title ASC')
        @sn = true;
      else
        @links = Link.all.paginate(page: params[:page], per_page: 10).order('title DESC')
        @sn = false;
      end
    elsif params[:sortScore]
      if params[:sortScore] == "desc"
        @links = Link.all.paginate(page: params[:page], per_page: 10).order('((cached_votes_up + 1.9208) / (cached_votes_up + cached_votes_down) - 1.96 * ((cached_votes_up * cached_votes_down) / (cached_votes_up + cached_votes_down) + 0.9604) / (cached_votes_up + cached_votes_down)) / (1 + 3.8416 / (cached_votes_up + cached_votes_down)) DESC')
        @ss = true;
      else
        @links = Link.all.paginate(page: params[:page], per_page: 10).order('((cached_votes_up + 1.9208) / (cached_votes_up + cached_votes_down) - 1.96 * ((cached_votes_up * cached_votes_down) / (cached_votes_up + cached_votes_down) + 0.9604) / (cached_votes_up + cached_votes_down)) / (1 + 3.8416 / (cached_votes_up + cached_votes_down)) ASC')
        @ss = false;
      end
    else
       @links = Link.all.paginate(page: params[:page], per_page: 10)
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /links/1
  # GET /links/1.json
  def show
    if params[:sortDate]
      @link = Link.find(params[:id])
      if params[:sortDate] == "desc"
        @sd = true;
        @comments = @link.comments.paginate(page: params[:page], per_page: 10).order('created_at DESC')
      else
        @sd = false;
        @comments = @link.comments.paginate(page: params[:page], per_page: 10).order('created_at ASC')
      end
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  # GET /links/new
  def new
    @blokadaURL = false
    @link = current_user.links.build
  end

  # GET /links/1/edit
  def edit
    @blokadaURL = true
  end

  # POST /links
  # POST /links.json
  def create
    @link = current_user.links.build(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to @link, notice: 'Link został pomyślnie dodany.' }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1
  # PATCH/PUT /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to @link, notice: 'Link został pomyślnie edytowany.' }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1
  # DELETE /links/1.json
  def destroy
    @link.destroy
    respond_to do |format|
      format.html { redirect_to links_url, notice: 'Link został pomyślnie usunięty.' }
      format.json { head :no_content }
    end
  end

  def upvote
    @link = Link.find(params[:id])
    @link.upvote_by current_user
    redirect_to :back
  end

  def downvote
    @link = Link.find(params[:id])
    @link.downvote_from current_user
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
      @comments = @link.comments.paginate(page: params[:page], per_page: 10).order('created_at ASC')
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def link_params
      params.require(:link).permit(:title, :url)
    end

end

app/helpers/links_helper.rb
module LinksHelper
end

app/views/links/_form.html.erb
<%= form_for(@link) do |f| %>
  <% if @link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
      <% @link.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label "Tytuł" %><br>
    <%= f.text_field :title, class: "form-control", required: true %>
  </div>
  <div class="form-group">
    <%= f.label "Link" %><br>
    <% if !@blokadaURL %>
      <%= f.text_field :url, class: "form-control", required: true %>
    <% end %>
    <% if @blokadaURL %>
      <%= f.text_field :url, class: "form-control", required: true, readonly: "true" %>
    <% end %>
  </div>
  <br>
  <div class="form-group">
    <%= f.submit "Prześlij", class: "btn btn-primary" %>
  </div>

<% end %>

app/views/links/_link.html.erb
<% if link.user == current_user || !@my %>
  <% begin %>
    <% @object = LinkThumbnailer.generate(link.url) %> 
    <% @e = false  %>
    <% rescue %>
      <% @e = true %>
  <% end %>
  <div class="link row clearfix">
    <h2>
      <%= link_to link.title, link %> <%= link.ci_lower_bound(link.get_upvotes.size, link.get_upvotes.size+link.get_downvotes.size, 0.95) %>%<br>
      <% if !@e && @object.images && @object.images.first %>
        <a href="<%= link.url %>" target="_blank" title="<%= link.title %>" ><img src="<%= @object.images.first.src.to_s %>" class="miniaturka" ></a></br>
      <% else %>
        <a href="<%= link.url %>" target="_blank" title="<%= link.title %>" ><img src="http://s10.ifotos.pl/img/brakzdjec_sapeppe.gif" class="miniaturka" ></a></br>
      <% end %>
      <small class="author">Przesłane <%= time_ago_in_words(link.created_at) %> temu przez <%= link.user.name %></small>
    </h2>
    <div class="btn-group">
      <a class="btn btn-default btn-sm btn-outline" href="<%= link.url %>" target="_blank" title="Odwiedź link">Odwiedź link</a>
      <%= link_to link, class: "btn btn-default btn-sm btn-outline", title: "Komentarze" do %>
        <span class="glyphicon glyphicon-comment"></span>
      <% end %>
      <% if user_signed_in? %>
        <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm btn-outline" do %>
          <span class="glyphicon glyphicon-thumbs-up"></span>
          <%= link.get_upvotes.size %>
        <% end %>
        <%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm btn-outline" do %>
          <span class="glyphicon glyphicon-thumbs-down"></span>
          <%= link.get_downvotes.size %>
        <% end %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/links/edit.html.erb
<h1 class = "text-center">Edytuj Link</h1>

<%= render 'form', link: @link %>

<!-- <%= link_to 'Show', @link %> | -->
  <div class = "przycisk"><%= link_to '', links_path, class: "btn btn-default btn-outline fa fa-reply ", title: "Wróć" %></div>

app/views/links/index.html.erb
<%= form_tag(links_path, :method => "get") do %>
  <ul class="nav navbar-nav pull-left">
    <li>
      <div class="input-group">
        <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Wyszukaj" %>
        <span class="input-group-btn">
          <button type="submit" class="btn btn-default btn-outline", title="Wyszukaj" ><span class="glyphicon glyphicon-search"></span></button>
        </span>
      </div>
    </li>
  </ul>
<% end %>

<ul class="nav navbar-nav pull-right">
  <% if user_signed_in? %>
    <% if @my %>
      <li><div class = "przycisk"><%= link_to '', { :all => "view" }, class: "btn btn-default btn-outline glyphicon glyphicon-eye-open", title: "Pokaż wszystkie strony" %></div></li>
    <% else %>
      <li><div class = "przycisk"><%= link_to '', { :my => "view" }, class: "btn btn-default btn-outline glyphicon glyphicon-eye-close", title: "Pokaż moje strony" %></div></li>
    <% end %>
  <% end %>
  <li><div class = "przycisk"><%= link_to '', hashtags_path, class: "btn btn-default btn-outline glyphicon glyphicon-tags", title: "Hasztagi" %></div></li>
  <li><div class= "btn-group odstepL">
    <% if @sd %>
      <%= link_to '', { :sortDate => "asc" }, class: "btn btn-default btn-outline rozmiar3 glyphicon glyphicon-sort-by-order", title: "Sortuj wg daty - rosnąco" %>
    <% else %>
      <%= link_to '', { :sortDate => "desc" }, class: "btn btn-default btn-outline rozmiar3 glyphicon glyphicon-sort-by-order-alt", title: "Sortuj wg daty - malejąco" %>
    <% end %>
    <% if @sn %>
      <%= link_to '', { :sortName => "desc" }, class: "btn btn-default btn-outline rozmiar3 glyphicon glyphicon-sort-by-alphabet-alt", title: "Sortuj wg tytułu - malejąco" %>
    <% else %>
      <%= link_to '', { :sortName => "asc" }, class: "btn btn-default btn-outline rozmiar3 glyphicon glyphicon-sort-by-alphabet", title: "Sortuj wg tytułu - rosnąco" %>
    <% end %>
    <% if @ss %>
      <%= link_to '', { :sortScore => "asc" }, class: "btn btn-default btn-outline rozmiar3 glyphicon glyphicon-sort-by-attributes", title: "Sortuj wg ilości rankingu- rosnąco" %>
    <% else %>
      <%= link_to '', { :sortScore => "desc" }, class: "btn btn-default btn-outline rozmiar3 glyphicon glyphicon-sort-by-attributes-alt", title: "Sortuj wg rankingu - malejąco" %>
    <% end %>
  </div></li>
</ul>
<br>
<% @links.each do |link| %>
  <% if link.user == current_user || !@my %>
    <% begin %>
      <% @object = LinkThumbnailer.generate(link.url) %>
      <% @e = false  %>
      <% rescue %>
        <% @e = true %>
    <% end %>
    <div class="link row clearfix">
      <h2>
        <%= link_to link.title, link %> <%= link.ci_lower_bound(link.get_upvotes.size, link.get_upvotes.size+link.get_downvotes.size, 0.95) %>%<br>
        <% if !@e && @object.images && @object.images.first %>
          <a href="<%= link.url %>" target="_blank" title="<%= link.title %>" ><img src="<%= @object.images.first.src.to_s %>" class="miniaturka" ></a></br>
        <% else %>
          <a href="<%= link.url %>" target="_blank" title="<%= link.title %>" ><img src="http://s10.ifotos.pl/img/brakzdjec_sapeppe.gif" class="miniaturka" ></a></br>
        <% end %>
        <small class="author">Przesłane <%= time_ago_in_words(link.created_at) %> temu przez <%= link.user.name %></small>
      </h2>
      <div class="btn-group">
        <a class="btn btn-default btn-sm btn-outline" href="<%= link.url %>" target="_blank" title="Odwiedź link">Odwiedź link</a>
        <%= link_to link, class: "btn btn-default btn-sm btn-outline", title: "Komentarze" do %>
                <span class="glyphicon glyphicon-comment"></span>
        <% end %>
        <% if user_signed_in? %>
          <%= link_to like_link_path(link), method: :put, class: "btn btn-default btn-sm btn-outline" do %>
            <span class="glyphicon glyphicon-thumbs-up"></span>
            <%= link.get_upvotes.size %>
          <% end %>
          <%= link_to dislike_link_path(link), method: :put, class: "btn btn-default btn-sm btn-outline" do %>
            <span class="glyphicon glyphicon-thumbs-down"></span>
            <%= link.get_downvotes.size %>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>
<% end %>

<div id="infinite-scrolling">
  <%= will_paginate @links, renderer: BootstrapPagination::Rails %>
</div>

app/views/links/index.js.erb
$('#content').append('<%= j render @links %>');
<% if @links.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @links, renderer: BootstrapPagination::Rails %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/links/new.html.erb
<h1 class = "text-center">Dodaj Link</h1>

<%= render 'form', link: @link %>
  	<div class = "przycisk"><%= link_to '', links_path, class: "btn btn-default btn-outline fa fa-reply ", title: "Wróć" %></div>

app/views/links/show.html.erb
<script>
		$(document).ready(function()
		{
		    $("#b").click(function(){
		      var text = document.getElementById("kom");
		      text.value = text.value.substring(0, text.selectionStart) +
		      '[b]'+text.value.substring(text.selectionStart, text.selectionEnd)+'[/b]'+text.value.substring(text.selectionEnd);
        });
        $("#i").click(function(){
		      var text = document.getElementById("kom");
		      text.value = text.value.substring(0, text.selectionStart) +
		      '[i]'+text.value.substring(text.selectionStart, text.selectionEnd)+'[/i]'+text.value.substring(text.selectionEnd);
        });
        $("#u").click(function(){
		      var text = document.getElementById("kom");
		      text.value = text.value.substring(0, text.selectionStart) +
		      '[u]'+text.value.substring(text.selectionStart, text.selectionEnd)+'[/u]'+text.value.substring(text.selectionEnd);
        });
          $("#s").click(function(){
		      var text = document.getElementById("kom");
		      text.value = text.value.substring(0, text.selectionStart) +
		      '[s]'+text.value.substring(text.selectionStart, text.selectionEnd)+'[/s]'+text.value.substring(text.selectionEnd);
        });
		});
	</script>
  <% begin %>
    <% @object = LinkThumbnailer.generate(@link.url) %>
    <% @e = false  %>
    <% rescue %>
      <% @e = true %>
  <% end %>
<ul class="nav navbar-nav pull-right">
    <li><div class = "przycisk"><%= link_to '', links_path, class: "btn btn-default btn-outline fa fa-reply ", title: "Wróć" %></div></li>
</ul>

<div class="page-header">
  <h1><a href="<%= @link.url %>", target="_blank"><%= @link.title %></a> <%= @link.ci_lower_bound(@link.get_upvotes.size, @link.get_upvotes.size+@link.get_downvotes.size, 0.95) %>%</h1>
  <% if !@e && @object.images && @object.images.first %>
    <a href="<%= @link.url %>" target="_blank" title="<%= @link.title %>" ><img src="<%= @object.images.first.src.to_s %>" class="miniaturka" ></a>
  <% else %>
    <a href="<%= @link.url %>" target="_blank" title="<%= @link.title %>" ><img src="http://s10.ifotos.pl/img/brakzdjec_sapeppe.gif" class="miniaturka" ></a></br>
  <% end %>
  <h1><small>Przesłane przez: <%= @link.user.name %></small></h1>
</div>

<div class="btn-group">
	<%= link_to 'Odwiedź link', @link.url, class: "btn btn-primary", target: "_blank", title: "Odwiedź link" %>
</div>

<div class="btn-group pull-right">
  <% if user_signed_in? %>
  <%= link_to like_link_path(@link), method: :put, class: "btn btn-default btn-sm btn-outline " do %>
    <span class="glyphicon glyphicon-thumbs-up"></span>
    <%= @link.get_upvotes.size %>
  <% end %>
  <%= link_to dislike_link_path(@link), method: :put, class: "btn btn-default btn-sm btn-outline " do %>
    <span class="glyphicon glyphicon-thumbs-down"></span>
    <%= @link.get_downvotes.size %>
  <% end %>
  <% end %>
</div>

<% if @link.user == current_user -%>
	<div class="btn-group">
		<%= link_to '', edit_link_path(@link), class: "btn btn-default glyphicon glyphicon-pencil btn-outline", title: "Edytuj" %>
		<%= link_to '', @link, method: :delete, data: { confirm: 'Na pewno?' }, class: "btn btn-default glyphicon glyphicon-trash btn-outline", title: "Usuń"  %>
	</div>
<% end %>

<% if !user_signed_in? %>
    <% if @sd %>
      <%= link_to '', { :sortDate => "asc" }, class: "btn btn-default btn-outline rozmiar3 glyphicon glyphicon-sort-by-order", title: "Sortuj wg daty - rosnąco" %>
    <% else %>
      <%= link_to '', { :sortDate => "desc" }, class: "btn btn-default btn-outline rozmiar3 glyphicon glyphicon-sort-by-order-alt", title: "Sortuj wg daty - malejąco" %>
    <% end %>
<% end %>

<% if user_signed_in? %>
</br></br></br>
<%= simple_form_for [@link, Comment.new]  do |f| %>
  <div class="field">
    <%= f.text_area :body, id: "kom", class: "form-control", required: true %>
  </div>
  <br>
  <ul class="nav navbar-nav pull-left">
    <li><%= f.submit "Dodaj komentarz", class: "btn btn-primary", title: "Dodaj komentarz" %></li>
    <% if @sd %>
      <%  @sd = @link.comments.order('created_at DESC') %>
      <%= link_to '', { :sortDate => "asc" }, class: "btn btn-default btn-outline rozmiar3 glyphicon glyphicon-sort-by-order", title: "Sortuj wg daty - rosnąco" %>
    <% else %>
      <%  @sd = @link.comments.order('created_at ASC') %>
      <%= link_to '', { :sortDate => "desc" }, class: "btn btn-default btn-outline rozmiar3 glyphicon glyphicon-sort-by-order-alt", title: "Sortuj wg daty - malejąco" %>
    <% end %>
  </ul>
  <ul class="nav navbar-nav pull-right">
    <div class= "btn-group">
      <a id="b" class="btn btn-default btn-outline rozmiar2" title="Pogrubienie"><span class="fa fa-bold"></span></a>
      <a id="i" class="btn btn-default btn-outline rozmiar2" title="Kursywa"><span class="fa fa-italic"></span></a>
      <a id="u" class="btn btn-default btn-outline rozmiar2" title="Podkreślenie"><span class="fa fa-underline"></span></a>
      <a id="s" class="btn btn-default btn-outline rozmiar2" title="Przekreślenie"><span class="fa fa-strikethrough"></span></a>
      <a class="btn btn-default btn-outline rozmiar2" href="/pages/emots.html" target="_blank" title="Dostępne emotikony"><span class="fa fa-smile-o"></span></a>
    </div>
  </ul>
<% end %>
<% end %>

<h3 class="comments_title">
  <%= @comments.count %>
  <% if @comments.count === 0 || @comments.count >= 5  %>
  komentarzy
  <% elsif @comments.count === 1 %>
  komentarz
  <% else %>
  komentarze
  <% end %>
</h3>
<div id="comments">
  <%= render :partial => @comments %>
</div>
<div id="infinite-scrolling">
	   <%= will_paginate @comments, renderer: BootstrapPagination::Rails %>
</div>

app/views/links/show.js.erb
console.log('show.js.erb links');
$('#content').append('<div id="comments"><%= j render @comments %></div>');
<% if @comments.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @comments, renderer: BootstrapPagination::Rails, id: comments %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>