config/routes.rb
Rails.application.routes.draw do
  get "hashtags/:hashtag",   to: "hashtags#show",      as: :hashtag
  get "hashtags",            to: "hashtags#index",     as: :hashtags
  devise_for :users
    resources :links do
    member do
      put "like", to:    "links#upvote"
      put "dislike", to: "links#downvote"
    end
    resources :comments
  end
  root to: "links#index"
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wypok</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<header class="navbar navbar-default" role="navigation">
    <div class="navbar-inner">
      <div class="container">
        <div id="logo" class="navbar-brand"><%= link_to "Wypok", root_path, class: "btn-default btn-outline my-radius none-underline" %></div>
        <nav class="navbar-collapse navbar-ex1-collapse"> <!-- collapse  -->
        	<% if user_signed_in? -%>
						<ul class="nav navbar-nav pull-right">
							<li><div class = "przycisk menu"><%= link_to '', new_link_path, class: "btn btn-default btn-outline btn-circle  glyphicon glyphicon-plus", title: "Dodaj link" %></div></li>
							<li><div class = "przycisk menu"><%= link_to '', edit_user_registration_path, class: "btn btn-default btn-outline btn-circle  glyphicon glyphicon-cog", title: "Zmień ustawienia konta" %></div></li>
							<li><div class = "przycisk menu"><%= link_to '', destroy_user_session_path, :method => :delete , class: "btn btn-default btn-outline btn-circle  glyphicon glyphicon-log-out", title: "Wyloguj" %></div></li>
						</ul>
					<% else -%>
						<ul class="nav navbar-nav pull-right">
							<li><div class = "przycisk menu"><%= link_to '', new_user_registration_path, class: "btn btn-default btn-outline btn-circle glyphicon glyphicon-user", title: "Zarejestruj" %></div></li>
							<li><div class = "przycisk menu"><%= link_to '', new_user_session_path, class: "btn btn-default btn-outline btn-circle glyphicon glyphicon-log-in", title: "Zaloguj" %></div></li>
						</ul>
					<% end -%>
        </nav>
      </div>
    </div>
  </header>

	<div id="main_content"> <!-- class="container" -->
		<div class="container">
			<% flash.each do |name, msg| %>
				<%= content_tag(:div, msg, class: "alert alert-info") %>
			<% end %>
		</div>

			<div id="content" class="col-md-9 center-block">
				<%= yield %>
			</div>
		</div>
	</div>
</body>
<script>
  $(function () {
    if ($('#infinite-scrolling .pagination li').size() > 0) {
      $(window).on('scroll', function() {
        var more_posts_url = $('.pagination .next a').attr('href');
          if (more_posts_url && $(window).scrollTop() > $(document).height() - $(window).height() - 60) {
            $('.pagination').html('<%= image_tag('ajax-loader.gif') %>');
            console.log(more_posts_url);
            $.getScript(more_posts_url);
          }
      });
    }
  });
</script>
</html>